### PR TITLE
Add goreleaser config & a CI step for release

### PR DESCRIPTION
**Pull request by rbehjati**
Based on https://goreleaser.com/quick-start/

### CODE REVIEW

**Comment by rbehjati** [comment]
@tiziano88 I am not sure if it will work, but let's try :)

**Review by tiziano88 — APPROVED** [review]

**Comment by rbehjati** [comment]
The `Run GoReleaser` step did not run. I'll look into it.

**Comment by tiziano88** [comment]
> The `Run GoReleaser` step did not run. I'll look into it.

I thought you set it up to run only when pushing tags, right?

https://github.com/project-oak/transparent-release/blob/bbc3f15bc25d157612df2730789b7d94a0dc0804/.github/workflows/release.yml#L28

**Comment by rbehjati** [comment]
Yes. Not sure how to push tags to main though. I think I have to create a tag on main manually.

**Pull request merged**
