### PR TITLE
Souffle Binary with Static C++ Runtime Libs

### PR DESCRIPTION
**Pull request by aferr**
This PR fixes the CI regression by using a souffle binary that statically links the C/C++ runtime libraries. See also https://github.com/google-research/raksha/pull/484

### CODE REVIEW

**Review by tiziano88 — APPROVED** [review]
Thanks for the quick fix!

**Comment by rbehjati** [comment]
I am still getting the same error when I run `bazel build //...` locally. Is a specific version of `bazel` needed for this to work?

**Comment by tiziano88** [comment]
> I am still getting the same error when I run `bazel build //...` locally. Is a specific version of `bazel` needed for this to work?

It seems to work in CI though, or is it not being run there yet?

**Comment by aferr** [comment]
> I am still getting the same error when I run `bazel build //...` locally. Is a specific version of `bazel` needed for this to work?

What sort of machine are you running this on? It will only work on linux machines. I can run it on a glinux cloudtop instance.

Sadly I think pulling in binaries is never going to be 100% self-contained.

**Comment by rbehjati** [comment]
I am running it on my gLinux. 

Yes, it seems to run on CI. So it is very strange that it is failing for me locally.

**Comment by aferr** [comment]
> > It seems to work in CI though, or is it not being run there yet?
> 
> Yes, it is running in CI. The authorization logic test is covered in build-all and AFAICT github is not taking crash faults today :)

Yikes... I meant to reply but edited your comment. Sorry about that.

**Comment by rbehjati** [comment]
The error is `failed to locate mcpp pre-processor`. Is that familiar?

**Comment by rbehjati** [comment]
I think it would nice to have development guidelines for this, but I noticed that we don't yet have a `docs/DEVELOPMENT.md` file. Would be nice to add that in a separate PR.

**Review by rbehjati — APPROVED** [review]

**Pull request merged**
